# Generated by Django 6.0.2 on 2026-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
       migrations.AddField(
    model_name='orderitem',
    name='price',
    field=models.IntegerField(default=0),
)
    ]
